### PR TITLE
Xano Improvements

### PR DESCRIPTION
**Pull request by AlexisJC**

### CODE REVIEW

**Comment by caffeinatedwes** [comment]
@AlexisJC Exciting stuff! Would this allow both A) custom headers to be configured for collections configured with the Xano plugin and B) API requests made to Xano in a workflow configured with the Xano plugin?

**Comment by AlexisJC** [comment]
> @AlexisJC Exciting stuff! Would this allow both A) custom headers to be configured for collections configured with the Xano plugin and B) API requests made to Xano in a workflow configured with the Xano plugin?

Hi, yes, it will allow you ta configure custom headers at collection and action level for everthing related to Xano :)

**Review by Dams-d — APPROVED** [review]

**Comment by caffeinatedwes** [comment]
giphy (14)

**Comment by caffeinatedwes** [comment]
Can't wait! 

giphy (15)

**Pull request merged**
